version: '3.4'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: torn_hackathon
      MYSQL_USER: torn
      MYSQL_PASSWORD: torn1234
      TZ: Etc/GMT
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations/:/migrations
    command:
      - -path=/migrations/
      - -database
      - mysql://torn:torn1234@tcp(mysql:3306)/torn_hackathon
      - up
  server:
    build:
      dockerfile: build/Dockerfile
      context: .
    volumes:
      - ./root:/var/www/html/root
      - ./public:/var/www/html/public
      - ./cron/cron:/home/root/cron
    ports:
      - 8080:80
    environment:
      DB_HOST: mysql
      DB_PASS: torn1234
      DB_USER: torn
      DB_NAME: torn_hackathon
      DB_PORT: 3306
      API_KEY: ${API_KEY}
